services:
  apache:
    build: .
    container_name: apache-server
    #ports: 
    #  - "8080:80"
    restart: unless-stopped
    networks:
      - internal-network
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-tunnel
    depends_on:
      - apache
    command:
      - "http"
      - "apache-server:80"
    environment:
      NGROK_AUTHTOKEN: 2wHMu7dfu5VadQxmnw0nzdbsBlT_2Xai418r4fF6nHVzoV1wR
    ports:
      - 4040:4040
    restart: unless-stopped
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge